source :gemcutter

gem 'eventmachine', '= 1.0.0.beta.4'
gem 'i18n'
gem 'tzinfo'
#gem 'activerecord'
gem 'activesupport'
gem 'actionpack'
#gem 'em-http-request'
#gem 'nokogiri'
#gem 'htmlentities'
gem 'json'
gem 'bitly'
gem 'chronic'
gem 'rufus-scheduler'
#gem 'mysql'
#gem 'em-websocket'
gem 'thin', '1.3.1'
gem 'sinatra', '1.3.1', :require => 'sinatra/base'
gem 'async_sinatra'
#gem 'sinatra-flash'
#gem 'haml'
#gem 'rdiscount'
#gem 'bson_ext'
#gem 'mongo_mapper'
#gem 'sequel'
#gem 'sqlite3'
gem 'colorize'
gem 'ripl-readline-em'
gem 'ripl-color_result'